# Generated by Django 4.2.20 on 2026-02-28 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mood_text', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(100)])),
                ('predicted_emotion', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
