# Generated by Django 4.2.20 on 2026-02-28 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='gratitude',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='habits',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='sleep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
